"""
SQLAlchemy ORM model for stored analyses.
Tracks original text, sentiment, confidence, summary, keywords,
stats, and XAI feature details per anonymous session.
"""
import uuid
from datetime import datetime, timezone

from sqlalchemy import Column, String, Float, Integer, Text, JSON, DateTime, func
from sqlalchemy.dialects.postgresql import UUID as PG_UUID
from sqlalchemy import TypeDecorator, String as SAString
from app.database import Base


class UUIDType(TypeDecorator):
    """
    Cross-database UUID column type.
    - On PostgreSQL: uses native UUID type for efficiency
    - On SQLite: stores as VARCHAR(36) string (local development)
    This avoids having two separate model definitions for dev vs prod.
    """
    impl = SAString(36)
    cache_ok = True

    def load_dialect_impl(self, dialect):
        if dialect.name == "postgresql":
            return dialect.type_descriptor(PG_UUID(as_uuid=False))
        return dialect.type_descriptor(SAString(36))

    def process_bind_param(self, value, dialect):
        if value is None:
            return value
        return str(value)

    def process_result_value(self, value, dialect):
        if value is None:
            return value
        return str(value)


class Analysis(Base):
    __tablename__ = "analyses"

    # Primary key — UUID generated by Python, stored as native UUID on PostgreSQL
    id = Column(UUIDType, primary_key=True, default=lambda: str(uuid.uuid4()))

    # Session UUID groups analyses for one anonymous user (indexed for fast history lookup)
    session_id = Column(UUIDType, index=True, nullable=False)

    # Raw user review text after cleaning
    original_text = Column(Text, nullable=False)

    # Extractive summary of the review (top 2-3 sentences by frequency score)
    summary = Column(Text, nullable=False)

    # Predicted sentiment label: "Positive", "Negative", or "Neutral"
    sentiment = Column(String(20), nullable=False)

    # Confidence score from predict_proba — float between 0.0 and 1.0
    confidence = Column(Float, nullable=False)

    # Top 5 keywords extracted by frequency (JSON array of strings)
    keywords = Column(JSON, nullable=False)

    # XAI influential words (JSON array of {"word": str, "score": float})
    top_influential_words = Column(JSON, nullable=False)

    # Text metric counters
    word_count = Column(Integer, nullable=False)
    sentence_count = Column(Integer, nullable=False)
    reading_time_seconds = Column(Integer, nullable=False)

    # Timestamp — set by the database server to avoid timezone drift
    created_at = Column(
        DateTime(timezone=True),
        server_default=func.now(),   # DB sets this, not Python — more reliable
        nullable=False,
    )
